
services:
  postgres6:
    image: postgres:latest
    container_name: german_vocab_db
    environment:
      POSTGRES_USER: abdi
      POSTGRES_PASSWORD: abdi
      POSTGRES_DB: german_vocab
    ports:
      - "5437:5432"
    volumes:
      - postgres_data7:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U abdi"]
      interval: 5s
      timeout: 5s
      retries: 5
  languagesea:
    image: abdirrahman29/languagesea:v1
    ports:
      - '3006:3000'
    environment:
      - DATABASE_URL=postgresql://abdi:abdi@localhost:5437/german_vocab
    
    deploy:
      resources:
        limits:
          memory: 1024M
    depends_on:
      - postgres6
   
 

volumes:
  postgres_data7:
